
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[360] =
    {   0,
        0,    0,   32,   30,   29,   14,   30,   28,   14,   16,
       30,    1,   14,   14,   14,    1,   14,   23,   23,   17,
       15,   18,   15,   16,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       16,   14,   15,    0,   26,    0,   28,   18,   17,    0,
        0,   14,   24,    0,    3,   24,   21,    0,    0,   24,
        0,   23,    0,    0,    0,    0,   23,    0,   16,   16,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
        6,   28,   28,   28,   28,   28,   28,   28,   28,    6,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,   28,    0,
        0,   27,    0,    0,   24,   24,    0,    0,    0,    0,
        3,   24,    0,   21,   21,    0,    0,   20,    0,   24,
        0,   22,   21,   20,   22,   23,    0,   23,   16,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,    4,   28,   28,
       28,   10,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       11,   28,   28,   28,    0,    0,    0,    0,    0,   24,
        0,    2,   24,    0,    0,   24,   20,   20,    0,   24,

       24,    0,    0,    0,   22,   22,    0,    0,   21,    0,
       20,    0,   22,    0,   23,    0,   28,   28,   28,   28,
        8,    9,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,    5,   28,   28,   28,   28,   12,   28,   19,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,    7,   28,   28,   25,   28,   28,   24,    0,   24,
        0,    0,    0,    0,   22,    0,    0,   24,   22,    0,
       22,    0,   22,    0,   28,   28,   28,   10,   13,   28,
       28,   28,   28,   11,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,    8,   28,

       28,   24,   22,    0,   24,   24,    0,   22,   22,   22,
        0,   22,   22,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   24,
       24,    0,   22,   22,   22,   22,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,    9,   28,   28,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    5,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   28,   30,   31,   30,
        5,    5,    5,    5,    5,   32,    5,    5,    5,   33,
        5,    5,    5,    5,    5,    5,    5,   34,    5,    5,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,    5,   49,   50,   51,   52,
       53,   54,    5,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    3,    6,    3,    1,    1,    1,    1,    7,    5,
        5,    5,    5,    5,    5,    3,    3,    3,    3,    3,
        3,    3,    3,    6,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[377] =
    {   0,
        0,    0,  965, 1051, 1051,  939,   64,    0,  938,   62,
      922, 1051,  932,   58,   57,   55,   68,   86,  133, 1051,
       53,  931,   55,  930,   53,   33,   49,   66,   61,   84,
      901,   40,  900,   68,   83,  897,   98,   43,  887,  892,
       96, 1051, 1051,  110, 1051,  180,    0, 1051, 1051,  930,
      234, 1051,  275,  926,    0,  149,  306,  342,  122, 1051,
      189, 1051,  371,  194,  125,  400,  205,  210,  911,  148,
      879,  878,  876,  884,  870,  125,  886,  885,  872,  866,
      852,  853,  850,  850,  856,  853,  847,  844,  840,    0,
      842,  129,  843,  826,  822,  831,  829,   80,  829,  812,

      815,  104,  813,  818,  802,  141,  178,  154,  804,  241,
      246, 1051,  254,  261,    0, 1051,  290,  313,  839,  146,
        0,  429,  357,    0, 1051,  386,  415,  438,  280,  446,
        0,  475,  461,  492,  526,    0,  543,  566,  824,  791,
      798,  791,  800,  795,  793,  788,  769,  767,  134,  774,
      771,  767,  753,  759,  746,  759,  752,    0,  732,  167,
      726,  737,  733,  729,  726,  718,  707,  708,  713,  703,
      663,  657,  659,  662,  648,  661,  646,  647,  647,  640,
        0,  627,  629,  614,  517,  183,  347,  653,  322,  571,
      223, 1051,    0,  576,  376,  600,  590, 1051,  229,  607,

     1051,  614,  314,  222,  637,  234,  671,  436,    0,  654,
      669,  444,  709,  494,    0,  677,  605,  596,  605,  587,
        0,    0,  576,  557,  555,  563,  551,  556,  552,  559,
      552,  543,    0,  555,  543,  541,  524,    0,  519,    0,
      537,  535,  530,  525,  517,  495,  503,  508,  494,  499,
      493,    0,  479,  482,    0,  475,  486,  725,  692,  739,
      754,  605,  703,  608,    0,  609,  715,  777,  815,  489,
        0,  708,  844,  487,  483,  455,  462,    0,    0,  447,
      447,  443,  443,  434,  431,  414,  406,  412,  409,  406,
      394,  397,  396,  385,  385,  369,  377,  368,  366,  362,

      361,  770,    0,  369,    0,  747,  468,    0,  873,    0,
      359,    0,  902,  342,  331,  324,  323,  323,  308,  314,
      312,  308,  302,  300,  278,  284,  275,  278,  267,  808,
     1051,  859,    0,  931,    0,    0,  259,  271,  261,  268,
      261,  246,  233,  233,  232,  239,  200,  203,  204,  200,
      193,  148,  139,  130,  108,    0,  105,   92, 1051,  976,
      981,  988,  995, 1002, 1009,   92, 1016, 1019, 1022, 1025,
     1028, 1031, 1034, 1037, 1040, 1043
    } ;

static yyconst flex_int16_t yy_def[377] =
    {   0,
      359,    1,  359,  359,  359,  359,  360,  361,  359,  359,
      362,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      359,  359,  359,  360,  359,  359,  361,  359,  359,  359,
      359,  359,  359,  363,  364,  359,  359,  359,  359,  359,
      359,  359,  365,  359,  359,  365,   19,  359,  359,  359,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  361,  360,
      360,  359,  359,  359,   53,  359,  359,  359,  363,  363,
      364,  359,  359,   57,  359,  359,  359,  359,  359,  359,
      366,  367,   57,  359,  367,   67,  359,   67,  359,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  360,  360,  359,  359,  359,  359,
      363,  359,  122,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  368,  366,  135,  366,  366,  369,  133,  359,
      359,  359,  135,  370,  138,  359,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  359,  359,  359,
      359,  368,  359,  368,  205,  371,  359,  359,  205,  372,
      213,  373,  213,  374,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,

      361,  359,  269,  375,  268,  368,  268,  205,  205,  273,
      376,  213,  135,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  359,
      359,  359,  269,  309,  273,  135,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,    0,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359
    } ;

static yyconst flex_int16_t yy_nxt[1119] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   12,
       13,   14,   12,   15,   16,   17,   18,   19,   19,   19,
       19,   20,   12,   21,   22,   23,   20,    8,    8,    8,
        8,    8,    8,    8,   12,    4,   12,   24,    8,   25,
       26,   27,   28,   29,   30,   31,    8,   32,    8,   33,
        8,   34,    8,   35,   36,   37,   38,    8,   39,   40,
        8,    8,    8,   12,   41,   12,   42,   45,   49,   52,
       52,   53,   53,   53,   53,   53,   69,   43,   54,   43,
       70,   48,   48,   55,   90,   73,   48,   74,   76,  106,
       91,   92,   48,   71,   75,   77,  203,  107,   78,   46,

       56,   79,   57,   57,   57,   57,   58,   94,   72,   80,
       82,   95,   83,   45,   59,   60,   61,   62,   81,   63,
       48,   84,   97,   85,   64,   96,   65,  167,   60,   61,
       60,   86,  168,   87,   90,   62,   88,   98,  128,  128,
       99,  134,  134,  172,  101,   46,   66,   56,  358,   67,
       67,   67,   67,   67,  102,  103,  191,  104,  173,  105,
       49,  192,   60,   61,   62,  122,  122,  122,  122,  122,
      357,   68,   48,  139,  356,   60,   61,   60,   60,  123,
      145,  146,   62,   44,  161,  162,   45,   44,  177,  225,
      226,   60,  123,   60,  252,  178,  110,  110,  110,  111,

      129,  182,  129,  183,  278,  130,  130,  130,  130,  130,
      133,  133,  133,  133,   58,   44,  234,  179,   46,  235,
       44,  136,  136,  136,  136,  136,  138,  138,  138,  138,
      138,   44,   64,  191,   44,  180,   44,   50,  359,  181,
      355,   50,  252,  137,   45,  197,  197,  181,   68,   45,
      113,  113,  113,  114,  263,  354,  353,  185,  185,  185,
      185,  112,  186,  186,  186,  186,  263,  199,  112,   50,
      187,  187,  187,  187,   50,  263,   46,  188,  188,  188,
      188,   46,  279,  352,  351,   50,  238,  263,   50,  350,
       50,  115,  115,  115,  115,  115,  130,  130,  130,  130,

      130,  189,  349,  189,  116,  117,  190,  190,  190,  190,
      190,  348,  347,  118,  158,  158,  346,  116,  117,  116,
       56,  345,  124,  124,  124,  124,   58,  344,  343,  115,
      115,  115,  115,  115,  342,   60,   61,  125,  190,  190,
      190,  190,  190,   90,  126,  233,  263,  341,   60,   61,
       60,  118,  264,  340,  112,  125,   56,  339,   58,   58,
       58,   58,   58,  188,  188,  188,  188,  263,  195,  238,
      195,   60,   61,  196,  196,  196,  196,  196,  278,  233,
      127,  338,   90,  337,   60,   61,   60,  132,  132,  132,
      132,  132,  196,  196,  196,  196,  196,  311,  132,  132,

      132,  132,  124,  124,  124,  124,   58,  304,  329,  328,
      132,  132,  132,  132,  132,  132,  135,  135,  135,  135,
      135,  222,  327,  233,  126,  326,  181,  135,  135,  135,
      135,   58,   58,   58,   58,   58,  222,  221,  325,  135,
      135,  135,  135,  135,  135,  193,  193,  193,  193,  193,
      324,  323,  279,  127,  197,  197,  322,  321,   60,  123,
      211,  211,  200,  200,  200,  200,  200,  194,  263,  198,
      221,   60,  123,   60,  270,  201,  199,  209,  209,  209,
      209,  320,  212,  319,  202,  318,  252,  198,  201,  263,
      201,  205,  205,  205,  205,  205,  317,  262,  316,  210,

      359,  315,  205,  205,  205,  205,  206,  207,  211,  211,
      262,  233,  262,  208,  205,  205,  205,  205,  205,  205,
       45,  359,  314,  198,  206,  274,  263,  270,  207,  158,
      212,  301,  274,  186,  186,  186,  186,  300,  299,  298,
      297,  198,  213,  213,  213,  213,  213,  263,  279,  296,
      295,  278,   46,  213,  213,  213,  213,  206,  207,  136,
      136,  136,  136,  136,  214,  213,  213,  213,  213,  213,
      213,  294,  293,  292,  291,  206,  290,  289,  288,  207,
      287,  137,  215,  215,  215,  215,  215,  258,  258,  258,
      258,  258,  193,  193,  193,  193,  193,  286,  285,  279,

      116,  284,  255,  283,  216,  282,  197,  197,  281,  259,
      280,  279,  238,  116,  194,  116,  260,  260,  260,  260,
      260,  198,  278,  200,  200,  200,  200,  200,  199,   60,
      200,  200,  200,  200,  200,  252,  201,  263,  261,  198,
      359,  263,   60,  264,   60,  202,  264,  304,  277,  201,
      276,  201,  202,  265,  265,  265,  265,  265,  263,  275,
      112,  359,  263,  257,  265,  265,  265,  265,  256,  238,
      209,  209,  209,  209,   58,  266,  265,  265,  265,  265,
      265,  265,  267,  255,  267,  211,  211,  268,  268,  268,
      268,  268,  210,  215,  215,  215,  215,  215,  254,  253,

      198,  252,  251,  263,  250,  249,  248,  212,  258,  258,
      258,  258,  258,  247,  267,  216,  267,  246,  198,  302,
      302,  302,  302,  302,  263,  271,  271,  271,  271,  271,
      259,  302,  302,  302,  302,  302,  271,  271,  271,  271,
      263,  258,  258,  258,  258,  258,  311,  272,  271,  271,
      271,  271,  271,  271,  116,  260,  260,  260,  260,  260,
      245,  263,  244,  259,  243,  242,  241,  116,   60,  116,
      260,  260,  260,  260,  260,  240,  239,  261,  238,  263,
      237,   60,  236,   60,  233,  264,  330,  330,  330,  330,
      330,  232,  261,  305,  305,  305,  305,  305,  231,  331,

      263,  230,  229,  222,  262,  262,  306,  262,  332,  263,
      221,  228,  331,  227,  331,  307,  262,  262,  262,  306,
      262,  306,  224,  181,  330,  330,  330,  330,  330,  223,
      263,  308,  308,  308,  308,  308,  222,  331,  221,  220,
      219,  218,  308,  308,  308,  308,  332,  217,   48,  120,
      331,  184,  331,  176,  308,  308,  308,  308,  308,  308,
      312,  312,  312,  312,  312,  175,  174,  171,  170,  169,
      166,  312,  312,  312,  312,  330,  330,  330,  330,  330,
      165,  158,  164,  312,  312,  312,  312,  312,  312,  334,
      334,  334,  334,  334,  163,  160,  159,  332,  158,  157,

      334,  334,  334,  334,  156,  155,  154,  153,  152,  151,
      150,  208,  334,  334,  334,  334,  334,  334,  336,  336,
      336,  336,  336,  149,  148,  147,  144,  143,  142,  336,
      336,  336,  336,  141,  140,   48,  120,  112,  109,  108,
      100,  336,  336,  336,  336,  336,  336,  205,  205,  205,
      205,  205,   93,   89,   48,   43,   48,   51,  205,  205,
      205,  205,   48,   43,  359,  359,  359,  359,  359,  359,
      205,  205,  205,  205,  205,  205,   44,   44,   44,   44,
       44,   44,   44,   47,  359,   47,   47,   47,   50,   50,
       50,  359,   50,   50,   50,  119,  119,  119,  119,  119,

      119,  119,  121,  359,  121,  121,  121,  121,  121,  131,
      359,  131,  131,  131,  131,  131,  204,  359,  204,  204,
      204,  204,  204,  262,  262,  262,  269,  269,  269,  273,
      273,  273,  303,  303,  303,  309,  359,  309,  310,  310,
      310,  313,  359,  313,  333,  359,  333,  335,  359,  335,
        3,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359
    } ;

static yyconst flex_int16_t yy_chk[1119] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,   10,   14,
       15,   16,   16,   16,   16,   16,   21,   21,   17,   23,
       23,   15,   14,   17,   32,   26,   10,   26,   27,   38,
       32,   32,   17,   25,   26,   27,  366,   38,   27,    7,

       18,   27,   18,   18,   18,   18,   18,   34,   25,   28,
       29,   34,   29,   44,   18,   18,   18,   18,   28,   18,
       41,   29,   35,   30,   18,   34,   18,   98,   18,   18,
       18,   30,   98,   30,  358,   18,   30,   35,   59,   59,
       35,   65,   65,  102,   37,   44,   18,   19,  357,   19,
       19,   19,   19,   19,   37,   37,  120,   37,  102,   37,
       41,  120,   19,   19,   19,   56,   56,   56,   56,   56,
      355,   19,   70,   70,  354,   19,   19,   19,   56,   56,
       76,   76,   19,   46,   92,   92,  186,   46,  106,  149,
      149,   56,   56,   56,  353,  106,   46,   46,   46,   46,

       61,  108,   61,  108,  352,   61,   61,   61,   61,   61,
       64,   64,   64,   64,   64,   46,  160,  107,  186,  160,
       46,   67,   67,   67,   67,   67,   68,   68,   68,   68,
       68,   46,   64,  191,   46,  107,   46,   51,  191,  107,
      351,   51,  350,   67,  110,  199,  199,  349,   68,  111,
       51,   51,   51,   51,  204,  348,  347,  110,  110,  110,
      110,  113,  111,  111,  111,  111,  206,  199,  114,   51,
      113,  113,  113,  113,   51,  204,  110,  114,  114,  114,
      114,  111,  346,  345,  344,   51,  343,  206,   51,  342,
       51,   53,   53,   53,   53,   53,  129,  129,  129,  129,

      129,  117,  341,  117,   53,   53,  117,  117,  117,  117,
      117,  340,  339,   53,  338,  337,  329,   53,   53,   53,
       57,  328,   57,   57,   57,   57,   57,  327,  326,  118,
      118,  118,  118,  118,  325,   57,   57,   57,  189,  189,
      189,  189,  189,  324,   57,  323,  203,  322,   57,   57,
       57,  118,  203,  321,  187,   57,   58,  320,   58,   58,
       58,   58,   58,  187,  187,  187,  187,  203,  123,  319,
      123,   58,   58,  123,  123,  123,  123,  123,  318,  317,
       58,  316,  315,  314,   58,   58,   58,   63,   63,   63,
       63,   63,  195,  195,  195,  195,  195,  311,   63,   63,

       63,   63,  126,  126,  126,  126,  126,  304,  301,  300,
       63,   63,   63,   63,   63,   63,   66,   66,   66,   66,
       66,  299,  298,  297,  126,  296,  295,   66,   66,   66,
       66,  127,  127,  127,  127,  127,  294,  293,  292,   66,
       66,   66,   66,   66,   66,  122,  122,  122,  122,  122,
      291,  290,  289,  127,  128,  128,  288,  287,  122,  122,
      212,  212,  130,  130,  130,  130,  130,  122,  208,  128,
      286,  122,  122,  122,  208,  130,  128,  133,  133,  133,
      133,  285,  212,  284,  130,  283,  282,  128,  130,  208,
      130,  132,  132,  132,  132,  132,  281,  307,  280,  133,

      307,  277,  132,  132,  132,  132,  132,  132,  134,  134,
      307,  276,  307,  132,  132,  132,  132,  132,  132,  132,
      185,  307,  275,  134,  132,  274,  214,  270,  132,  257,
      134,  256,  214,  185,  185,  185,  185,  254,  253,  251,
      250,  134,  135,  135,  135,  135,  135,  214,  249,  248,
      247,  246,  185,  135,  135,  135,  135,  135,  135,  137,
      137,  137,  137,  137,  135,  135,  135,  135,  135,  135,
      135,  245,  244,  243,  242,  135,  241,  239,  237,  135,
      236,  137,  138,  138,  138,  138,  138,  190,  190,  190,
      190,  190,  194,  194,  194,  194,  194,  235,  234,  232,

      190,  231,  230,  229,  138,  228,  197,  197,  227,  190,
      226,  225,  224,  190,  194,  190,  196,  196,  196,  196,
      196,  197,  223,  200,  200,  200,  200,  200,  197,  196,
      202,  202,  202,  202,  202,  220,  200,  262,  196,  197,
      264,  266,  196,  262,  196,  200,  264,  266,  219,  200,
      218,  200,  202,  205,  205,  205,  205,  205,  262,  217,
      188,  264,  266,  184,  205,  205,  205,  205,  183,  182,
      210,  210,  210,  210,  210,  205,  205,  205,  205,  205,
      205,  205,  207,  180,  207,  211,  211,  207,  207,  207,
      207,  207,  210,  216,  216,  216,  216,  216,  179,  178,

      211,  177,  176,  207,  175,  174,  173,  211,  259,  259,
      259,  259,  259,  172,  263,  216,  263,  171,  211,  263,
      263,  263,  263,  263,  207,  213,  213,  213,  213,  213,
      259,  267,  267,  267,  267,  267,  213,  213,  213,  213,
      272,  258,  258,  258,  258,  258,  272,  213,  213,  213,
      213,  213,  213,  213,  258,  260,  260,  260,  260,  260,
      170,  272,  169,  258,  168,  167,  166,  258,  260,  258,
      261,  261,  261,  261,  261,  165,  164,  260,  163,  306,
      162,  260,  161,  260,  159,  306,  302,  302,  302,  302,
      302,  157,  261,  268,  268,  268,  268,  268,  156,  302,

      306,  155,  154,  153,  268,  268,  268,  268,  302,  268,
      152,  151,  302,  150,  302,  268,  268,  268,  268,  268,
      268,  268,  148,  147,  330,  330,  330,  330,  330,  146,
      268,  269,  269,  269,  269,  269,  145,  330,  144,  143,
      142,  141,  269,  269,  269,  269,  330,  140,  139,  119,
      330,  109,  330,  105,  269,  269,  269,  269,  269,  269,
      273,  273,  273,  273,  273,  104,  103,  101,  100,   99,
       97,  273,  273,  273,  273,  332,  332,  332,  332,  332,
       96,   95,   94,  273,  273,  273,  273,  273,  273,  309,
      309,  309,  309,  309,   93,   91,   89,  332,   88,   87,

      309,  309,  309,  309,   86,   85,   84,   83,   82,   81,
       80,  309,  309,  309,  309,  309,  309,  309,  313,  313,
      313,  313,  313,   79,   78,   77,   75,   74,   73,  313,
      313,  313,  313,   72,   71,   69,   54,   50,   40,   39,
       36,  313,  313,  313,  313,  313,  313,  334,  334,  334,
      334,  334,   33,   31,   24,   22,   13,   11,  334,  334,
      334,  334,    9,    6,    3,    0,    0,    0,    0,    0,
      334,  334,  334,  334,  334,  334,  360,  360,  360,  360,
      360,  360,  360,  361,    0,  361,  361,  361,  362,  362,
      362,    0,  362,  362,  362,  363,  363,  363,  363,  363,

      363,  363,  364,    0,  364,  364,  364,  364,  364,  365,
        0,  365,  365,  365,  365,  365,  367,    0,  367,  367,
      367,  367,  367,  368,  368,  368,  369,  369,  369,  370,
      370,  370,  371,  371,  371,  372,    0,  372,  373,  373,
      373,  374,    0,  374,  375,    0,  375,  376,    0,  376,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[32] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mylex.l"
#line 2 "mylex.l"
#include "lexer.h"	
/* DECIMAL LITERAL */
/* HEXADECIMAL LITERAL */
/* OCTAL LITERAL */
/* BINARY LITERAL */
/* FLOATING POINT LITERAL */
/* Escape Sequence */
#line 845 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 78 "mylex.l"

#line 1027 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 360 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1051 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 79 "mylex.l"
{printf("\n\n TOKEN_NAME: Separator\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 80 "mylex.l"
{return -1;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 81 "mylex.l"
{return -1;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 82 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 83 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 84 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 85 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 86 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 87 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 88 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 89 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 91 "mylex.l"
{printf("\n\n TOKEN_NAME: Keyword\t\t\t VALUE: %s",yytext); return -1;}   	         
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 92 "mylex.l"
{printf("\n\n TOKEN_NAME: Arithmetic operator\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 93 "mylex.l"
{printf("\n\n TOKEN_NAME: Relational operator\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 94 "mylex.l"
{printf("\n\n TOKEN_NAME: Arithmetic operator\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 95 "mylex.l"
{printf("\n\n TOKEN_NAME: Conditional operator\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 96 "mylex.l"
{printf("\n\n TOKEN_NAME: Assignment operator\t VALUE: %s",yytext); return -1;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 97 "mylex.l"
{printf("\n\n TOKEN_NAME: NULL Literal\t\t VALUE: %s",yytext);return NULL_LITERAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 98 "mylex.l"
{printf("\n\n TOKEN_NAME: Integer Literal\t\t VALUE: %s",yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 99 "mylex.l"
{printf("\n\n TOKEN_NAME: Integer Literal\t\t VALUE: %s",yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 100 "mylex.l"
{printf("\n\n TOKEN_NAME: Integer Literal\t\t VALUE: %s",yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 101 "mylex.l"
{printf("\n\n TOKEN_NAME: Integer Literal\t\t VALUE: %s",yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 102 "mylex.l"
{printf("\n\n TOKEN_NAME: Float Literal\t\t VALUE: %s",yytext); return FLOAT_LITERAL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 103 "mylex.l"
{printf("\n\n TOKEN_NAME: Boolean Literal\t\t VALUE: %s",yytext); return BOOLEAN_LITERAL;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 105 "mylex.l"
{printf("\n\n TOKEN_NAME: String Literal\t\t VALUE: %s",yytext); return STRING_LITERAL;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 106 "mylex.l"
{printf("\n\n TOKEN_NAME: Character Literal\t\t VALUE: %s",yytext); return CHAR_LITERAL;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "mylex.l"
{printf("\n\n TOKEN_NAME: Identifier\t\t\t VALUE: %s",yytext); return IDENTIFIER;}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 108 "mylex.l"
{return -1;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 109 "mylex.l"
{return -1;};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 110 "mylex.l"
ECHO;
	YY_BREAK
#line 1279 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 360 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 360 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 359);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 110 "mylex.l"


int yywrap(void){
	return 1;
}


